# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Оля\OneDrive\Документы\GitHub\predprof\addZaezd.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_Race(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(569, 583)
        self.name_race = QtWidgets.QPlainTextEdit(Form)
        self.name_race.setGeometry(QtCore.QRect(280, 10, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.name_race.setFont(font)
        self.name_race.setObjectName("name_race")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(9, 10, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.type_race = QtWidgets.QLabel(Form)
        self.type_race.setGeometry(QtCore.QRect(10, 90, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.type_race.setFont(font)
        self.type_race.setObjectName("type_race")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 170, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pilot_1 = QtWidgets.QPlainTextEdit(Form)
        self.pilot_1.setGeometry(QtCore.QRect(280, 170, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pilot_1.setFont(font)
        self.pilot_1.setObjectName("pilot_1")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(340, 510, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        lst = ['qualifying (квалификация)', 'top 32(1 / 16)', 'top 16(1 / 8)', 'top 8(четвертьфинал)', 'semifinal(полуфинал)',
            'battle for 3rd place (заезд за 3 место)',
               'final (финал)']
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(280, 100, 281, 41))
        self.comboBox.setObjectName("comboBox")
        for i in range(len(lst)):
            self.comboBox.addItem(lst[i])

        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 250, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pilot2 = QtWidgets.QPlainTextEdit(Form)
        self.pilot2.setGeometry(QtCore.QRect(280, 250, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pilot2.setFont(font)
        self.pilot2.setObjectName("pilot2")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 330, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.ip_2 = QtWidgets.QPlainTextEdit(Form)
        self.ip_2.setGeometry(QtCore.QRect(280, 410, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ip_2.setFont(font)
        self.ip_2.setObjectName("ip_2")
        self.ip_1 = QtWidgets.QPlainTextEdit(Form)
        self.ip_1.setGeometry(QtCore.QRect(280, 330, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ip_1.setFont(font)
        self.ip_1.setObjectName("ip_1")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(10, 410, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Добавить заезд"))
        self.label.setText(_translate("Form", "id Соревнования"))
        self.type_race.setText(_translate("Form", "Тип заезда"))
        self.label_3.setText(_translate("Form", "Номер пилота 1"))
        self.pushButton.setText(_translate("Form", "Добавить"))
        self.label_4.setText(_translate("Form", "Номер пилота 2"))
        self.label_5.setText(_translate("Form", "ip пилота 1"))
        self.label_6.setText(_translate("Form", "ip пилота 2"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
