# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Оля\OneDrive\Документы\GitHub\predprof\true.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1222, 711)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1291, 711))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.deleteFilmButton = QtWidgets.QPushButton(self.tab)
        self.deleteFilmButton.setGeometry(QtCore.QRect(200, 10, 151, 51))
        self.deleteFilmButton.setObjectName("deleteFilmButton")
        self.addFilmButton = QtWidgets.QPushButton(self.tab)
        self.addFilmButton.setGeometry(QtCore.QRect(20, 10, 151, 51))
        self.addFilmButton.setObjectName("addFilmButton")
        self.filmsTable = QtWidgets.QTableWidget(self.tab)
        self.filmsTable.setGeometry(QtCore.QRect(20, 80, 1181, 571))
        self.filmsTable.setObjectName("filmsTable")
        self.filmsTable.setColumnCount(0)
        self.filmsTable.setRowCount(0)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.addFilmButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.addFilmButton_2.setGeometry(QtCore.QRect(20, 10, 151, 51))
        self.addFilmButton_2.setObjectName("addFilmButton_2")
        self.deleteFilmButton_5 = QtWidgets.QPushButton(self.tab_2)
        self.deleteFilmButton_5.setGeometry(QtCore.QRect(200, 10, 151, 51))
        self.deleteFilmButton_5.setObjectName("deleteFilmButton_5")
        self.filmsTable_5 = QtWidgets.QTableWidget(self.tab_2)
        self.filmsTable_5.setGeometry(QtCore.QRect(20, 80, 1181, 571))
        self.filmsTable_5.setObjectName("filmsTable_5")
        self.filmsTable_5.setColumnCount(0)
        self.filmsTable_5.setRowCount(0)
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.exitAction = QtWidgets.QAction(MainWindow)
        self.exitAction.setObjectName("exitAction")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Система судейства"))
        self.deleteFilmButton.setText(_translate("MainWindow", "Удалить заезд"))
        self.addFilmButton.setText(_translate("MainWindow", "Добавить заезд"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.addFilmButton_2.setText(_translate("MainWindow", "Добавить заезд"))
        self.deleteFilmButton_5.setText(_translate("MainWindow", "Удалить заезд"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.exitAction.setText(_translate("MainWindow", "Выход"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
